exp_name: 0
save_dir: None

data:
  dataset: ImsVoxelsDataset
  # dataset: CoordsVoxelsDataset
  num_samples: 400
  data_dir: data
  pct_train: 0.8
  pct_val: 0.1
  pct_test: 0.1

train:
  load: true
  lr: 0.0001
  num_updates: 50000
  eval_interval: 10
  log_interval: 1
  save_interval: 10
  batch_size: 32

model:
  name: ConvDense
  # name: Dense
  # name: DenseDeconv

optimizer:

evaluate:
  val: False
  batch_size: 10